# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: openssl
  version: 3.5.1
source:
  url: https://github.com/openssl/openssl/releases/download/openssl-3.5.1/openssl-3.5.1.tar.gz
  sha256: 529043b15cffa5f36077a4d0af83f3de399807181d607441d734196d889b641f
build:
  run_exports:
    - openssl >=3.5.1,<4.0a0
  number: 0
  string: h7b32b05_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_5
    - binutils_linux-64 2.43 h4852527_5
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 h6f18a23_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_5
    - libgcc 15.1.0 h767d61c_3
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 15.1.0 h69a702a_3
    - libgomp 15.1.0 h767d61c_3
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 15.1.0 h8f9b012_3
    - libxcrypt 4.4.36 hd590300_1
    - make 4.4.1 hb9d3cd8_2
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  run:
    - __glibc >=2.17,<3.0.a0
    - ca-certificates
    - libgcc >=13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_3
    - libgomp 15.1.0 h767d61c_3
test:
  requires:
    - pkg-config
    - ripgrep
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.5.1" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
about:
  home: https://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
extra:
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  feedstock-name: openssl
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250701.2.1
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 621e42b4a4d74986b958e22a25635e6497d57663
