# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: libiconv
  version: '1.18'
source:
  patches:
    - glibc.patch
  sha256: 3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz
build:
  number: 1
  run_exports:
    - libiconv >=1.18,<2.0a0
  string: h4ce23a2_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_3
    - binutils_linux-64 2.43 h4852527_3
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_7
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_3
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libtool 2.4.7 he02047a_1
    - make 4.4.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025a h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h77fa898_1
    - libgomp 14.2.0 h77fa898_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
test:
  commands:
    - test ! -f ${PREFIX}/bin/iconv
    - test_man_files=$(jq '.files[] | select( . | startswith("share/man"))' $CONDA_PREFIX/conda-meta/libiconv-1.18-${PKG_BUILD_STRING}.json)
    - if [[ ${test_man_files} ]]; then echo "found GPL licensed files being packaged
      ${test_man_files}"; exit 1; fi
    - test_doc_files=$(jq '.files[] | select( . | startswith("share/doc"))' $CONDA_PREFIX/conda-meta/libiconv-1.18-${PKG_BUILD_STRING}.json)
    - if [[ ${test_doc_files} ]]; then echo "found GPL licensed files being packaged
      ${test_doc_files}"; exit 1; fi
    - test -f $CONDA_PREFIX/lib/libiconv${SHLIB_EXT}
    - test -f $CONDA_PREFIX/lib/libcharset${SHLIB_EXT}
  requires:
    - jq
about:
  home: https://www.gnu.org/software/libiconv/
  license: LGPL-2.1-only
  license_file: COPYING.LIB
  summary: Provides iconv for systems which don't have one (or that cannot convert
    from/to Unicode.)
extra:
  copy_test_source_files: true
  feedstock-name: libiconv
  final: true
  flow_run_id: azure_20250221.1.1
  recipe-maintainers:
    - jakirkham
    - jhamman
    - mbargull
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/libiconv-feedstock
  sha: c257e75813b123103626964a999ad7babc79b824
