# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.1.0
source:
  fn: brotli-1.1.0.tar.gz
  url: https://github.com/google/brotli/archive/v1.1.0.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
build:
  ignore_run_exports_from:
    - brotli
  number: 3
  string: py312h2ec8cdc_3
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cmake 4.0.2 h74e3db0_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 h6f18a23_11
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 hb14504d_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.0 h5888daf_0
    - libgcc 15.1.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_1
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 he8ea267_2
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libstdcxx-ng 15.1.0 h4852527_2
    - libuv 1.51.0 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.12.1 hff21bea_1
    - openssl 3.5.0 h7b32b05_1
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli 1.1.0 hb9d3cd8_3
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.50.0 hee588c1_0
    - libstdcxx 15.1.0 h8f9b012_2
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.12.11 h9e4cc4f_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
  run_constrained:
    - libbrotlicommon 1.1.0 hb9d3cd8_3
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  dev_url: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250606.2.1
  remote_url: https://github.com/conda-forge/brotli-feedstock
  sha: 3b307fa1233138d5bca196a05d1a20d1c400baf3
