# This file created by conda-build 25.3.1
# ------------------------------------------------

package:
  name: simdjson
  version: 3.12.3
source:
  sha256: d0af071f2f4187d8b26b556e83ef832b634bd5feb4e2f537b9dabbd334d4e334
  url: https://github.com/simdjson/simdjson/archive/v3.12.3.tar.gz
build:
  number: 0
  run_exports:
    - simdjson >=3.12.3,<3.13.0a0
  string: h84d6215_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.4 hb9d3cd8_0
    - ca-certificates 2025.1.31 hbcca054_0
    - cmake 4.0.0 h74e3db0_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_8
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 h6834431_8
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libcurl 8.13.0 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.0 h5888daf_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.6.4 hb9d3cd8_0
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 he8ea267_2
    - libssh2 1.11.1 hf672d98_0
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libstdcxx-ng 14.2.0 h4852527_2
    - libuv 1.50.0 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.4.1 h7b32b05_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h767d61c_2
    - libgomp 14.2.0 h767d61c_2
    - libstdcxx 14.2.0 h8f9b012_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
test:
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - cmake
    - gxx_linux-64 13.*
    - ninja
about:
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  dev_url: https://github.com/simdjson/simdjson/
  doc_url: https://simdjson.github.io/simdjson/
  home: https://simdjson.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250403.2.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  remote_url: https://github.com/conda-forge/simdjson-feedstock
  sha: 8a1f70ea7fc2a04cfe30c858ce1c86d845c6e78d
