# This file created by conda-build 25.3.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Apr  8 15:55:37 2025
# ------------------------------------------------

package:
  name: c-ares
  version: 1.34.5
source:
  sha256: 7d935790e9af081c25c495fd13c2cfcda4792983418e96358ef6e7320ee06346
  url: https://github.com/c-ares/c-ares/releases/download/v1.34.5/c-ares-1.34.5.tar.gz
build:
  number: '0'
  run_exports:
    - c-ares >=1.34.5,<2.0a0
  string: hb9d3cd8_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - cmake-no-system 4.0.0 h5888daf_1
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_8
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-ng 14.2.0 h4852527_2
    - ninja 1.12.1 h297d8ca_0
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
  run_constraint:
    - c-ares-static <0a0
about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250408.2.1
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/c-ares-feedstock
  sha: 4a9135fee0af5ec00e64c24445e85ccfc411f34a
