# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 30 10:20:36 2024
# ------------------------------------------------

package:
  name: fontconfig
  version: 2.15.0
source:
  patches:
    - linux-custom-paths.patch
  sha256: f5f359d6332861bd497570848fcb42520964a9e83d5e3abe397b6b6db9bcaaf4
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.gz
build:
  binary_has_prefix_files:
    - lib/libfontconfig.so.1.*
  number: '1'
  run_exports:
    - fontconfig >=2.15.0,<3.0a0
    - fonts-conda-ecosystem
  string: h7e30c49_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_2
    - binutils_linux-64 2.43 h4852527_2
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.8.30 hbcca054_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_5
    - gperf 3.1 h9c3ff4c_0
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.3 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 13.3.0 heb74ff8_1
    - libsqlite 3.47.0 hadc24fc_1
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-ng 14.2.0 h4852527_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - meson 1.6.0 pyhd8ed1ab_0
    - ncurses 6.5 he02047a_1
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.3.2 hb9d3cd8_0
    - pkg-config 0.29.2 h4bc722e_1009
    - python 3.12.7 hc5c86c4_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - expat 2.6.3 h5888daf_0
    - freetype 2.12.1 h267a509_2
    - libexpat 2.6.3 h5888daf_0
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - libpng 1.6.44 hadc24fc_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - freetype >=2.12.1,<3.0a0
    - libexpat >=2.6.3,<3.0a0
    - libgcc >=13
    - libuuid >=2.38.1,<3.0a0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - fc-cache --help
    - fc-cat --help
    - fc-list
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help
    - test -f $PREFIX/lib/libfontconfig.a
    - test -f $PREFIX/lib/libfontconfig${SHLIB_EXT}
about:
  description: 'Fontconfig is a library designed to provide system-wide font configuration,

    customization and application access.

    '
  dev_url: https://cgit.freedesktop.org/fontconfig/
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: A library for configuring and customizing font access
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241030.1.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pkgw
  remote_url: https://github.com/conda-forge/fontconfig-feedstock
  sha: d78fa069b082a63d01f49c5b48ac893de223bbbc
