# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr 28 19:46:05 2025
# ------------------------------------------------

package:
  name: zstandard
  version: 0.23.0
source:
  patches:
    - patches/0001-link-zstd-statically.patch
    - patches/0002-Ensure-c-extension-looks-up-symbols-locally.patch
  sha256: b2d8c62d08e7255f68f7a740bae85b3c9b8e5466baa9cbf7f57f1cde0ac6bc09
  url: https://pypi.org/packages/source/z/zstandard/zstandard-0.23.0.tar.gz
build:
  number: '2'
  string: py312h66e93f0_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_10
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgomp 14.2.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 14.2.0 h8f9b012_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cffi 1.17.1 py312h06ac9bb_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 14.2.0 h767d61c_2
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.49.1 hee588c1_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-ng 14.2.0 h4852527_2
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_0
    - pip 25.1 pyh8b19718_0
    - pycparser 2.22 pyh29332c3_1
    - python 3.12.10 h9e4cc4f_0_cpython
    - python_abi 3.12 7_cp312
    - readline 8.2 h8c095d6_2
    - setuptools 79.0.1 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zstd 1.5.6 ha6fb4c9_0
    - zstd-static 1.5.6 hac33072_0
  run:
    - __glibc >=2.17,<3.0.a0
    - cffi >=1.11
    - libgcc >=13
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
    - LD_PRELOAD=$CONDA_PREFIX/lib/libzstd.so python run_test.py
  imports:
    - zstandard
  requires:
    - pip
    - zstd 1.5.7.*
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250428.1.1
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstandard-feedstock
  sha: 4fa8f180d8e326f573e476d10db3b8fac064a583
