# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 26 16:09:43 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.3.1
source:
  url: https://github.com/conda/menuinst/archive/2.3.1.tar.gz
  sha256: aaf1b141b78c3f193a968e01ea8ba8a9d25ab08c938f326437114fe108871280
build:
  number: '0'
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.3.1
  script:
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1753546258937/work/menuinst/data/osx_launcher_*"
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1753546258937/work/menuinst/data/appkit_launcher_*"
    - /home/conda/feedstock_root/build_artifacts/menuinst_1753546258937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - icu 75.1 he02047a_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - ld_impl_linux-64 2.44 h1423503_1
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_3
    - libgcc-ng 15.1.0 h69a702a_3
    - libgomp 15.1.0 h767d61c_3
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.3 hee844dc_1
    - libstdcxx 15.1.0 h8f9b012_3
    - libstdcxx-ng 15.1.0 h4852527_3
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.1 h7b32b05_0
    - packaging 25.0 pyh29332c3_1
    - pip 25.1.1 pyh8b19718_0
    - python 3.12.11 h9e4cc4f_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 8.3.1 pyhd8ed1ab_0
    - setuptools_scm 8.3.1 hd8ed1ab_0
    - tk 8.6.13 noxft_hd72426e_102
    - tomli 2.2.1 pyhd8ed1ab_1
    - typing-extensions 4.14.1 h4440ef1_0
    - typing_extensions 4.14.1 pyhe01879c_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
  run:
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - menuinst
    - menuinst.api
  commands: null
about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
  doc_url: https://conda.github.io/menuinst/
extra:
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250726.1.1
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: f969fef8ac70ffe4fbed2213cf22a6790fe84e63
