# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libcurl
  version: 8.14.1
source:
  url: http://curl.haxx.se/download/curl-8.14.1.tar.bz2
  sha256: 5760ed3c1a6aac68793fc502114f35c3e088e8cd5c084c2d044abdf646ee48fb
build:
  run_exports:
    - libcurl >=8.14.1,<9.0a0
  number: 0
  string: h332b0f4_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 h6f18a23_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libgcc 15.1.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgomp 15.1.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 15.1.0 h8f9b012_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - libnghttp2 1.64.0 h161d5f1_0
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_2
    - libstdcxx-ng 15.1.0 h4852527_2
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - __glibc >=2.17,<3.0.a0
    - krb5 >=1.21.3,<1.22.0a0
    - libgcc >=13
    - libnghttp2 >=1.64.0,<2.0a0
    - libssh2 >=1.11.1,<2.0a0
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.5.0,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
about:
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250604.2.1
  remote_url: https://github.com/conda-forge/curl-feedstock
  sha: 6dc1ed3d5de0175deaa1445098f8ab8fd0b77875
