# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libexpat
  version: 2.7.1
source:
  url: https://github.com/libexpat/libexpat/releases/download/R_2_7_1/expat-2.7.1.tar.bz2
  sha256: 45c98ae1e9b5127325d25186cf8c511fa814078e9efeae7987a574b482b79b3d
build:
  ignore_run_exports_from:
    - gxx_linux-64 14.*
  number: 0
  string: hecca717_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_3
    - gcc_linux-64 14.3.0 h1382650_11
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - gxx_impl_linux-64 14.3.0 he663afc_3
    - gxx_linux-64 14.3.0 ha7acb78_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_3
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_103
    - libgomp 15.1.0 h767d61c_3
    - libsanitizer 14.3.0 hd08acf3_3
    - libstdcxx 15.1.0 h8f9b012_3
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_103
    - make 4.4.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  run_constrained:
    - expat 2.7.1.*
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_3
    - libgomp 15.1.0 h767d61c_3
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  feedstock-name: expat
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250716.4.1
  remote_url: https://github.com/conda-forge/expat-feedstock
  sha: 6178cd15d555c99dc1be92f6f3a018a7d22fa666
