# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 13 06:44:08 2024
# ------------------------------------------------

package:
  name: icu
  version: '75.1'
source:
  - patches: null
    sha256: cb968df3e4d2e87e8b11c49a5d01c787bd13b9545280fc6642f826527618caef
    url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-src.tgz
  - folder: source/data
    sha256: a5104212dc317a64f9b035723ea706f2f4fd5a0f37b7923fae7aeb9d1d0061b1
    url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=75.1,<76.0a0
  string: he02047a_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_9
    - gcc_impl_linux-64 12.3.0 h58ffeeb_13
    - gcc_linux-64 12.3.0 h9528a6a_9
    - gxx_impl_linux-64 12.3.0 h2a574ab_13
    - gxx_linux-64 12.3.0 ha28b414_9
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.3.0 h6b66f73_113
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libsanitizer 12.3.0 hb8811af_13
    - libstdcxx-devel_linux-64 12.3.0 h6b66f73_113
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
    - libtool 2.4.7 h27087fc_0
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h0c530f3_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libstdcxx-ng 14.1.0 hc0a3c3a_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc-ng >=12
    - libstdcxx-ng >=12
test:
  commands:
    - test ! -f $PREFIX/lib/libicudata.a
    - test -f $PREFIX/lib/libicudata.so.75.1
    - test ! -f $PREFIX/lib/libicui18n.a
    - test -f $PREFIX/lib/libicui18n.so.75.1
    - test ! -f $PREFIX/lib/libicuio.a
    - test -f $PREFIX/lib/libicuio.so.75.1
    - test ! -f $PREFIX/lib/libicutest.a
    - test -f $PREFIX/lib/libicutest.so.75.1
    - test ! -f $PREFIX/lib/libicutu.a
    - test -f $PREFIX/lib/libicutu.so.75.1
    - test ! -f $PREFIX/lib/libicuuc.a
    - test -f $PREFIX/lib/libicuuc.so.75.1
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/
  home: https://icu.unicode.org
  license: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240713.1.1
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
  remote_url: https://github.com/conda-forge/icu-feedstock
  sha: dc39a238c7b171624dee6c0f1b0765e3a6abe868
