name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools (ruff, shellcheck)
        run: |
          python -m pip install --upgrade pip
          pip install --no-input ruff
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Shellcheck run_docking.sh (non-blocking)
        run: shellcheck run_docking.sh || true

      - name: Ruff lint (non-blocking)
        run: ruff check --output-format=github --exit-zero topn_by_target.py

      - name: Python syntax check
        run: python -m py_compile topn_by_target.py

